# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios-extension.rb'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'today-extension'
  app.frameworks << "NotificationCenter"
  app.info_plist['NSExtension'] = {
    'NSExtensionPrincipalClass' => 'TodayViewController',
    'NSExtensionPointIdentifier' => 'com.apple.widget-extension'
  }

  app.target('../../frameworks/framework-sample', :framework)
end
